### ISSUE TITLE
Extend Uploader to handle XNAT backend

### ISSUE THREAD

**Issue by kursawero** [ddRPB/rpb-uploader#59]

**Comment by toskrip** [comment]
Set the following DICOM tag in order to allow XNAT pre-archive auto project sorting...

> 0032,4000 StudyComments

`Project:StudySiteProtocolID  Subject:Pseudonym Session:md5hash_base_10_digit string_from_pseudonymised_StudyInstaceUID`

or

`Project:EDC-codePartnerSiteIdentifier  Subject:Pseudonym Session:md5hash_base_10_digit string_from_pseudonymised_StudyInstaceUID`

Careful crafted string as between project, subject and session there should be empty space.

Note: with on additional changes this would still store the incoming data in our RPB research PACS. However it would allow to push them to XNAT SCP where it would be automatically assigned to the project and subject a session created.

Note: if we would want to not store in PACS at all, we would need to adapt backend RPB and consider using new  HTTPImportServiceClient (Client-DIZXNAT-Master pipeline) to forward to XNAT SCP but here I am not sure if we want to go this road.

Note: there is no multi-centre support in XNAT and the idea is to have extra project for each study site in study.

**Comment by toskrip** [comment]
In uploader we actually know details about visit, in theory we could add something form visit details into Session identifier but first lets start without it.
